### ISSUE TITLE
Error on search on new project

### ISSUE THREAD

**Issue by kmilogp8496** [nuxt-themes/docus#1007]
After creating a new project and starting the dev server, the following error appears in console: 

`Uncaught SyntaxError: The requested module '/_nuxt/node_modules/.pnpm/@vueuse+integrations@10.6.1_focus-trap@7.5.4_fuse.js@6.6.2_vue@3.3.8/node_modules/@vueuse/integrations/useFuse.mjs?v=d41e5a87' does not provide an export named 'UseFuseOptions'`

Also, the search functionality does not work because of this.

The error comes from the component `components/app/AppSearch.vue` in the following import: 

`import { useFuse, UseFuseOptions } from '@vueuse/integrations/useFuse'`

**Comment by trc-mathieu** [comment]
This is due to a new compilerOptions that the nuxt team decided to set to true by default which require all type imports to be explicitly imported like `import type {useFuseOptions} from ...`
The fix was already made in the repo but in the meantime, you can just disable verbatimModuleSyntax by adding this in your nuxt.config
```
export default defineNuxtConfig({
  typescript: {
    tsConfig: {
      compilerOptions: {
        verbatimModuleSyntax: false
      }
    }
  }
})
```
This MR fixes it and is already merged so the fix would be in the next release: https://github.com/nuxt-themes/docus/pull/997

**Comment by LlamaTheHutt** [comment]
@trc-mathieu I've been looking all night for this. Thank you so much!
