### ISSUE TITLE
feat: mermaid integration

### ISSUE THREAD

**Issue by atinux** [nuxt-themes/docus#34]
See https://github.com/nuxt/content/issues/746#issuecomment-775884944

**Comment by chdecultot** [comment]
Hi @Atinux,

The issue is closed but here is a solution for people who want to integrate mermaid in Docus easily:


1. Create a new plugin called `mermaid.client.js`

```javascript
import mermaid from "mermaid/dist/mermaid"

export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.provide('mermaid', () => mermaid)
})
```

_We are using a plugin because if the import is directly in the component it breaks when reloading the page on a static site._

2. Create a new component in _components/content_ called `Mermaid.vue`

```vue
<template>
    <div class="mermaid" v-if="show">
        <slot></slot>
    </div>
</template>

<script setup>

let show = ref(false);

const { $mermaid } = useNuxtApp()

onMounted( async() => {
  show.value = true
  $mermaid().initialize({startOnLoad: true })
  await nextTick()
  $mermaid().init();
})

</script>
```

Then you can add a <mermaid> tag within your markdown with your mermaid syntax.

Have a nice day
