### ISSUE TITLE
feat: components playground

### ISSUE THREAD

**Issue by Tahul** [nuxt-themes/docus#478]
We need to create a component playground.

This will be really useful in the long term, and will also bring the theme development and improvement experience, as much as the authoring experience to a new level.

This should be included into admin and should include following features:
- Two panels UI
- a Docus template at right, with the component included 
- an UI splitted in 2 tabs at left
   - A tab showing the component props and slots, and the ability to fill these datas
   - A tab showing a snippet using our syntax, filled with the data from the UI

**Comment by GerryWilko** [comment]
What happened to this feature? Did it not make the cut/out-of-scope for Docus? I see you guys produced a really nice [`ComponentCard`](https://github.com/nuxtlabs/ui/blob/dev/docs/components/content/ComponentCard.vue) for your docs site on `@nuxthq/ui`. This kind of component actually feels like it has a place within the Docus world. Render a component and let you play with the props for it.

Personally I've never been a fan of things like Storybook/Histoire because they feel a little too inflexible and don't nicely slot into existing documentation sites favouring a fullscreen app approach instead.

Having something like that [`ComponentCard`](https://github.com/nuxtlabs/ui/blob/dev/docs/components/content/ComponentCard.vue)  component in Docus could provide a nice balance of prop playground without being too opinionated on how these types of things should be presented within docs.
