### ISSUE TITLE
Roadmap Request

### ISSUE THREAD

**Issue by harlan-zw** [nuxt-themes/docus#714]
Hi

Firstly, thanks for all the amazing work on Docus! It's shaping up really nicely.

I'm building a theme off of Docus and maintaining multiple documentation sites using Docus. Pretty much since I've started using Docus though, there have been breaking changes every time I've gone to update it. Either in the form of components changing, tokens changing or app config changing.

This isn't a problem if you're just using the document-driven markdown, but I need to make minor adjustments to the theme, which I think is a common use case.

This has turned into quite a time sink. It would just be nice to have some sort of roadmap/insight into when the project will stabilize (in terms of tokens/components changing).

Thanks :)

**Comment by Tahul** [comment]
Hello Harlan!

Since the last year we've released 3 different versions of Docus, and I have to say this has been a wild ride for all of us, as we've had to create, maintain and update many (a growing number) websites that were using it.

I share the pain you are mentioning here, and trust me that is something that will be avoided in the future.

One of the major pain points of the past year was Docus not being open-sourced, which kind of allowed used to ship breaking changes between iterations, and also was a clear signal (at least from the way we communicated around it) that it was going to happen. 

I'm sorry if this was unexpected, and if you have any issues with latest versions, or projects that needs updates, I would happily help you on that task.

All these iterations were a way for us to explore the concept of theming in Nuxt, it has accompanied us through the switch between Nuxt 2 and Nuxt 3, Docus being one of the first "projects" that were built on the earliest versions of the framework (even before Release Candidates).

Docus also has been the sandbox for Nuxt Content v2, it was the place in which we wrote the Document Driven mode, the place in which we first integrated Shiki as a syntax highlighter, where we first used Nuxt Component Meta, also was the first project that we were able to live-edit from the earliest versions of Nuxt Studio (back in 2021), and so many other contributions to the Nuxt ecosystem and products.

Since we open-sourced it, it is clearly stated that we will as much as possible limit the breaking changes.

Also, you can expect the open sourcing of Elements really soon, which also is a way for us to allow you to pin some versions of the components you are actually using in your content, and keep on receiving updates for the Docus theme itself.

In terms of release cycles, I think we will now follow semantic releases, and limit breaking changes to major versions.

I hope this clarifies why the last updates has been so painful, and reassure you that we want to ensure your experience with Docus is as good as possible! 🙏

Thank you so much for your feedback, feel free to reach me out if I can help you on an update!
