### ISSUE TITLE
bug: pages with dot in filename will throw 404

### ISSUE THREAD

**Issue by sent** [nuxt-themes/docus#737]
Hello,

Pages with dot in filename will throw 404 as they're not being generated, only the first one is generated.

See:

http://haraka.github.io/plugins/connect.p0f 404
http://haraka.github.io/plugins/data.headers 404
http://haraka.github.io/plugins/data.signatures 404

and this page works ?
http://haraka.github.io/plugins/connect.rdns_access 200

Repo: https://github.com/haraka/haraka.github.io

See files under: https://github.com/haraka/haraka.github.io/blob/master/content/8.plugins/ 

Thanks!

**Comment by Atinux** [comment]
I believe this might be a bug related to Nitro if he detects a path similar to a file extension 🤔 

Any hint on this @pi0 @farnabaz ?

**Comment by farnabaz** [comment]
Indeed this is related to Nitro's pre-renderer.
A temporary workaround is to add these urls into `nitro.prerender.routes` in `nuxt.config`.

**Comment by mathieunicolas** [comment]
This bug is definitely still here, and I just lost like 4 hours trying to figure out what's happening.
The prerendering is f up, I can't understand why it takes or not routes...
I checked in my older versions and last time I build with Docus 1.2.5 it was ok. Now, for a reason I can't explain, even if I downgrade Docus to 1.2.5, the nuxi generate command still takes Docus 1.3.1.
I deleted npm cache, node modules, npm install again, nothing...

**Comment by mathieunicolas** [comment]
In my Docus project, my content folder is fully structured with 0.folder, 1.folder, 0.file, etc, etc...
And it looks like just adding 0.folder1 and 1.folder2 in nitro.prerender.routes works, all the subfolders and files are rendered

**Comment by Tahul** [comment]
This issue seem to be resolved by previous comments, I'm closing for now but feel free to re-open. :)
