### ISSUE TITLE
Collapse some folders in _dir.yml 

### ISSUE THREAD

**Issue by mathieunicolas** [nuxt-themes/docus#743]
Hello there,

# The situation
Last Docus version
As a teacher, I would like to collapse every sections in the aside nav except those on which we are working.

# What I tried
I added `aside.collapsed: true` in `app.config.ts`.
I tried adding `collapsed: false` in `_dir.yml` but it seems the prop is not validated because it doesn't appear in Vue DevTools
I discovered adding the following instead makes `link.aside.collapse` appear in Vue DevTools : 
```
aside:
    collapsed: false
```
# What I finally did
I use a customized `DocsAsideTree.vue` with this function :

(I added the line `if(link.aside) { return link.aside.collapsed }`)

```ts
const isCollapsed = (link) => {
  if (link.children) {
    // Directory has been toggled manually, use its state
    if (typeof collapsedMap.value[link._path] !== 'undefined') {
      return collapsedMap.value[link._path]
    }

    if(link.aside) { return link.aside.collapsed }
    // Return value grabbed from the link
    if (link?.collapsed) { return link?.collapsed }

    if (docus.value.aside?.collapsed) { return docus.value.aside?.collapsed }
  }

  return false
}
```

That did the trick and I can now fine tune the collapsed state in the `DocsAsideTree` component.

# My question
1. Is this trick okay ? I don't know if the line I added is robust enough.
2. This could be a feature, what do you think about it ?
3. How can I modify the keys that are "accepted" in YML (for example, `collapsed` is not in Vue DevTools but `aside.collapsed` is ok), so in the future I could tweak more things, with other custom keys ?

Thanks a lot for Nuxt3, for Nuxt Content, for Docus... I'm so happy with all these new things !

# Bonus question
The website https://docus.dev loads pages instantly without any delay, and no loading bar.
My first tries hosted on netlify with `nuxi generate` show a small delay, and the loading bar. What is this magic ?

**Comment by Tahul** [comment]
Hello @mathieunicolas ;

I'm very interested in a PR that implements your change, we can check out the deploy and fine tune it to improve this feature!

If you look here:
https://github.com/nuxt-themes/docus/blob/aed892f82068a08622c4320bddc064987700a4f8/nuxt.config.ts#L69

You'll find out the `aside` key inside the `navigation.fields` key that allows to add more fields from front-matter to navigation objects!

About your bonus question, what method are you using to build?

Docus works in both Edge and Static targets, and Docus.dev is built statically, so that might be the difference!

I would advise on using Docus with Static mode, unless you have specific needs that requires you to use Edge!

You can build your Docus site statically using `nuxi generate` instead of `nuxi build`!

**Comment by mathieunicolas** [comment]
Thanks @Tahul for your quick answer !
I never did a PR so if it's okay with the mistakes I could make while doing my first one I can try !
Thanks for your information about the 69th line of `nuxt.config.ts`, I missed that one. 

About the bonus question, I just deploy the `npm run generate` output to netlify. Before answering, I checked few more things and it appears docus.dev runs smoothly without loading bar because I already visited all the pages, and they are cached, am I right ?

**Comment by Tahul** [comment]
Yes, pages are cached, and if you keep the website open and visit most pages, the parsed content will also stay in memory.

That makes the navigation instant between pages after first visit.
